### ISSUE TITLE
Elixir 1.7 Compatibility

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/shoehorn#11]
The Distillery release plugin seems to use some private APIs that no longer exist in elixir 1.7.0.

# Steps to reproduce
##  1) Create a new project
```
mix new test
cd test
asdf install elixir 1.7.0-otp21
asdf install erlang 21.0.1
asdf local elixir 1.7.0-otp21
asdf local erlang 21.0.1
```

## 2) Add distillery and shoehorn:
```elixir
{:shoehorn, "~> 0.3.1"},
{:distillery, "~> 1.5"}
```

## 3) Generate release config
```
mix release.init
```

## 4) Add plugin
```elixir
  plugin Shoehorn
```

## 5) Observe error
```
mix release
Compiling 1 file (.ex)
Generated test app
** (Mix.Releases.Config.LoadError) could not load release config rel/config.exs
    ** (UndefinedFunctionError) function Mix.Config.Agent.start_link/0 is undefined (module Mix.Config.Agent is not available)
    Mix.Config.Agent.start_link()
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:446: :erl_eval.expr/5
    (stdlib) erl_eval.erl:126: :erl_eval.exprs/5
    (elixir) lib/code.ex:232: Code.eval_string/3
    (distillery) lib/mix/lib/releases/config/config.ex:281: Mix.Releases.Config.read_string!/1
    (distillery) lib/mix/lib/releases/config/config.ex:302: Mix.Releases.Config.read!/1
```

## 6) Cry
:cry:

**Comment by tcoopman** [comment]
Already fixed in distillery master: https://github.com/bitwalker/distillery/issues/431

**Comment by mobileoverlord** [comment]
Fixed in master
